### PR TITLE
Issue43

### PR DESCRIPTION
**Pull request by astrikos**
Hi @JonasGroeger, this is an attempt to solve your issue #43. Could you clone and checkout to this branch and give it a try after you install using `python setup.py install`.
It would also be useful if you enable logging on the beginning of your script with something like:
```code
import logging
logging.basicConfig(level=logging.DEBUG)
for handler in logging.root.handlers:
    handler.addFilter(logging.Filter('atlas-stream'))
```
This way you can see if you if and when you are disconnecting.
Let me know if that works for you so I can merge and make a new release soon.

### CODE REVIEW

**Comment by JonasGroeger** [comment]
Hey @astrikos,

I'll be trying this when I find the time. Thanks so far :)

**Comment by JonasGroeger** [comment]
I tested this with a small script with the measurement ID from the Issue #43.

Steps to reproduce:

1. Start the script
2. Check if data is incoming
3. `ifdown eth0`
4. Wait for some time
5. `ifup eth0`

After 5., this output is generated:

```
DEBUG:atlas-stream:Disconnected from RIPE Atlas Stream
DEBUG:atlas-stream:Reconnected to RIPE Atlas Stream
DEBUG:atlas-stream:Trying to attach to existed subscriptions
DEBUG:atlas-stream:Subscribing to {'buffering': False, 'stream_type': 'result', 'msm': 4412911}
DEBUG:atlas-stream:Subscribed to subscription: {'buffering': False, 'stream_type': 'result', 'msm': 4412911}
```

After that, **the streaming continues**! Awesome!

**Comment by JonasGroeger** [comment]
Will this go into 1.3.1?

**Comment by JonasGroeger** [comment]
@astrikos You still need to include this patch. Almost forgot :)

```
--- stream-orig.py	2016-12-08 16:27:22.057539631 +0100
+++ stream.py	2016-12-08 16:27:11.669539432 +0100
@@ -56,7 +56,7 @@
 
     def on_atlas_subscribed(self, *args):
         LOG.debug("Subscribed to subscription: {}".format(args[0]))
-        hash_object = hashlib.sha1(str(args[0]))
+        hash_object = hashlib.sha1(str(args[0]).encode('utf-8'))
         hex_dig = hash_object.hexdigest()
         self.SUBSCRIPTIONS[hex_dig] = args[0]
 
```

else you will get 

```
  File "/home/jgroeger/.virtualenvs/project/lib/python3.5/site-packages/ripe/atlas/cousteau/stream.py", line 59, in on_atlas_subscribed
    hash_object = hashlib.sha1(str(args[0]))
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by astrikos** [comment]
okay covered that, with which subscription did you caused that? for a simple subscription in py2.7 it worked okay for me.

**Comment by JonasGroeger** [comment]
Those are a lot of coveralls reports :O

**Comment by astrikos** [comment]
Right, and since this file is not covered by any tests I missed it for py3. That's the reason also coveralls complains, there is no tests so the more we write to file the coverage drops.
Anyway, I will try to write some tests as soon as I find some time. I am merging that now.

**Pull request merged**
