### PR TITLE
Added option to perform a oneoff measurement

### PR DESCRIPTION
**Pull request by Woutifier**
It seems logical to have the option for a measurement to be oneoff

### CODE REVIEW

**Comment by astrikos** [comment]
Hi Wouter,
is_oneoff is a property of measurement itself (https://atlas.ripe.net/docs/measurement-creation-api/), so it should be inside every measurement itself.
Something like ping = Ping(af=4, target="www.google.gr", description="testing new wrapper", is_oneoff=True), which is already supported.
Would it be clearer if I add an oneoff example in the Readme?

**Comment by Woutifier** [comment]
Hi Astrikos,
The ripe atlas webinterface shows me this:
```
$ curl --dump-header - -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d '{
 "definitions": [
  {
   "af": 4,
   "query_class": "IN",
   "query_type": "A",
   "description": "DNS measurement",
   "use_probe_resolver": false,
   "resolve_on_probe": false,
   "use_NSID": false,
   "protocol": "UDP",
   "udp_payload_size": 512,
   "retry": 0,
   "qbuf": false,
   "noabuf": false,
   "prepend_probe_id": false,
   "recursion_desired": false,
   "do": false,
   "cd": false,
   "type": "dns"
  }
 ],
 "probes": [
  {
   "type": "area",
   "value": "WW",
   "requested": 50
  }
 ],
 "is_oneoff": true
}' https://atlas.ripe.net/api/v2/measurements?key=YOUR_KEY_HERE
```
As you can see the is_oneoff is part of the request as it is in the root of the json structure and not in the definitions. Am I somehow mistaken about this?

An example would indeed be helpful! :)

**Comment by Woutifier** [comment]
It appears as if there is a inconsistency between what the documentation specifies and what the webinterface does.

**Comment by danielquinn** [comment]
I think what you've stumbled onto here is a change in our API and the backward-compatibility code we added to make sure that things didn't break.

`is_oneoff` used to be defined in the `definition` block, but once we realised that was a mistake, we moved that into the so-called "timing" section and updated the documentation.  *The server code still supports both locations*, but only the timing section is considered appropriate.

We're slowly building up a new API version (/v2/) that will require (among other things) that `is_oneoff` only be specified in the timing section, and we'll be moving Cousteau toward that API in the coming weeks.  For users, this should be transparent though, which is why we haven't announced anything.  We probably won't publish anything until we have stabilised v2 and documented its deprecation of v1.

Anyway, your changes look good, and we'd like to include them, but they require one fix before we do.  Please change [this line](https://github.com/RIPE-NCC/ripe-atlas-cousteau/pull/3/files#diff-239dbbf77f622d7c775f26e4793c572cR109) to reference `/v2/` instead of `/v1/`, and that should put us on our way to accommodating the new API.

**Comment by Woutifier** [comment]
I've added the change to v2, thanks for your quick feedback!

**Comment by astrikos** [comment]
Okay, tests pass now as well so I am going to go ahead and merge that. It will make it to a new version after I finish with some other changes that I will finish this week. Thanks for the contrib!

**Pull request merged**
